model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    sane_index_shape: true
    embed_dim: 96
    n_embed: 1024
    image_key: null
    ddconfig:
      double_z: False
      z_channels: 96
      resolution: 64
      in_channels: 3
      out_ch: 3
      ch: 96
      ch_mult: [1,2,2,4,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 8
    train:
      target: taming.data.blinking_pattern.BlinkingTrain
      params:
        root: /data/hslee/discrete-jepa/runner/datasets/data/blinking_balls/4Balls_6Frames_Blinking_Count
        video_len: 1
        stochastic_sample: True
        size: 64
        output_discrete_pixel_value: False
    validation:
      target: taming.data.blinking_pattern.BlinkingTest
      params:
        root: /data/hslee/discrete-jepa/runner/datasets/data/blinking_balls/4Balls_6Frames_Blinking_Count
        video_len: 1
        stochastic_sample: True
        size: 64
        output_discrete_pixel_value: False

worldmodel:
  lr: 1e-3
  final_lr: 1e-6
  warmup_steps_pct: 0.15
  total_steps: 15000

seed: 2024